### ISSUE TITLE
PalginHsrNeoscrypt

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.5#198]
is fully tested and added tested with 6x10603gb & 6 x1080ti tested on all pools...
note: single card pc's may need a longer benchmark time instructions on how to do this is below..

note: benchmark time for PalginHsrNeo is min 10minutes max 18minutes

this is needed until PalginHsr adds a API to there Miner

All other algos are left at default benchmark time of 10mins per Algo

**Comment by Coinminer24** [comment]
Testing it now. Initially it didn't show up in my miner list, Kalust was there, but if I commented out Neo in there then palgin popped up

**Comment by Coinminer24** [comment]
Getting share rejected, invalid job ID, duplicate share etc... Any idea why?

**Comment by nemosminer** [comment]
Ok so all benchmarks are working for me except the Hsrneo. It runs for around 18 minutes on both my 1070 and 1070 ti and has shares reporting on the miner along with nice, but when it shows the hash rate on nemos it is 0. You can see the hash rate after x second = 0 when it goes to add it to the profit and switching list.

Update: Here are some screen grabs. I notice that the hash rate file for HSR is not loading the actual hash rate. I have tried quite a bit to get it to work including deleting the hash file and benching multiple times. Not sure why.

 @nemosminer
  Owner
nemosminer commented 12 hours ago • 
not sure all 9 of my rigs bench marked and are running fine with Palgin HSr ... whats wrong with your screen? Palgin won't read speed until the words "over speed is" is displayed in HSR miner window

re run and see if it passes

if you want to increase HSR benchmark

edit: include.ps1

find: "wrapper" {
do {
Start-Sleep 600 #plus 10mins to HSRNeo Benchmark

increase the 600

 @zzup
  
zzup commented 11 hours ago • 
This is what happened on 2 of my rigs. The screen issue is due to remoting into it and reducing the graphics quality. Basically it is just not refeshing the non changing parts of the screen.

It is strange as only HSR is doing the issue with 0 has being shown in the benchmark file even though it is roughly doing 1.3 mh/s

Update: Trying to increase the time now. I dont think i have seen the over speed is yet.

 @zzup
  
zzup commented 11 hours ago • 
OK it took 21 minutes to finally get this screenshot and it updated! Increased the 600 to 900 fixed it. Long but effective benchmark.
hsr7

This is a single 1070. Most of my systems are single card just being we are a family with quite a few gaming computers that mine well :)

 @nemosminer
  Owner
nemosminer commented 10 hours ago
yip single card rigs are the problem as it takes one card so long to get to the "overall speed is"
thats why i had to increase it to 18mins in the first place...

**Comment by pjdouillard** [comment]
On a system with a Titan Xp Collectors Edition, when the script tries to benchmark, it produces the following:
 INFO : [15:45:14] : Share Rejected, Job not found.
 INFO : [15:45:14] : Share Rejected, Job not found.
 INFO : [15:45:14] : Share Rejected, Job not found.
 INFO : [15:45:14] : Share Rejected, Job not found.
 INFO : [15:45:14] : Share Rejected, Job not found.
 INFO : [15:45:14] : Share Rejected, Job not found.
 INFO : [15:45:14] : Share Rejected, Job not found.

Then after a certain time, it seems to fix itsel:
INFO : [15:45:24] : New block #64460 received, new difficulty is 417.992
 INFO : [15:45:48] : New block #64461 received, new difficulty is 432.976
 INFO : [15:45:52] : New block #101811 received, new difficulty is 214.093
 INFO : [15:46:11] : GPU#0 - TITAN Xp COLLECTORS EDITION, speed is 8189.36kH/s

Why is this happening?

At the same time, when on other system, everything runs fine.

**Comment by joesixpack** [comment]
Yeah, HSRNeo is bugged on Ti's and the dev is MIA.  Have to stick to Klaust.

**Comment by nemosminer** [comment]
im not MIA 1080ti have the biggest improvment ! over KlausT +15% hashrate....

no bug 

i have two 6 x 1080ti rigs myself i can confirm the speed increase 

i don't own any Titan's so can't confirm.. KlausT may be better with Titan's

**Comment by pjdouillard** [comment]
How do I get that latest Klaust Algo and replace the one in your setup?

Nice Powershell scrip btw, really good to see there are still some skilled people knowing how to use it properly!

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner-v2.4.1/archive/master.zip

Best Regards
Nemo

**Comment by pjdouillard** [comment]
I see the miner was there, but what script do I need to modify to use it?
If only add back 'neoscrypt' to the .bat file, it will run the Hsr version.

Thx for any help.

**Comment by pjdouillard** [comment]
Ok finally found how:
1) edit file ccminerKlaust.ps1 in Miners folder and remove the comment on the Neoscrypt line.  Save the file.
2) edit file palginhsr.ps1 in Miners folder and comment out the Neoscrypt line. Save. 
3) Rerun your benchmark.
4) ...
5) Profit

**Comment by nemosminer** [comment]
edit: CcminerKlausT,ps1 

find:   #"neoscrypt" = " -d $SelGPUCC" #NeoScrypt

change to:   "neoscrypt" = " -d $SelGPUCC" #NeoScrypt

save

**Comment by cmbconcretefire** [comment]
Hey nemo, just wanted to say that the comment above "and the dev is MIA" ----- the way I read that, it sounded to me like they were talking about Palgin. Not you. :)

**Comment by pjdouillard** [comment]
The Klaust ccminer works great with the Titan Xp and 1080Ti.  The Titan Xp gives me 1.41 MH/s @ +125 Core/+500 Mem/70% Power.

**Comment by nemosminer** [comment]
i  get 1.61mhs from a 1080ti at 75+tdp(175watt( = 50 core =500 mem .............  KlausT can not keep up

**Comment by pjdouillard** [comment]
How do you make it work on a 1080 Ti?

**Comment by nemosminer** [comment]
same on pool...

**Comment by joesixpack** [comment]
Yeah, was talking about the Palgin dev.

It may run fine in the short term, but let it run 24 hours...

**Comment by RevngeSevnFold** [comment]
I cant get PalginHSR to finish benchmarking. I can see my hash rate and everything but the Benchmarking just won't finish(Stopped it after an hour) and save the damn hash rate. Tried the 900 sec on start still wont save the hash rate. Not sure why as I dont get or see any errors.

Rig I tried the upgrade on runs 2 1070's and one 1060 6GB

**Comment by nemosminer** [comment]
re added KlausT 

edit: CcminerKlausT,ps1

find: #"neoscrypt" = " -d $SelGPUCC" #NeoScrypt

change to: "neoscrypt" = " -d $SelGPUCC" #NeoScrypt

save

**Comment by yepla** [comment]
On my computer Palgin HSRNeoscrypt says valid share but on the pool it s only invalid share.
This miner not work for me i have switch back for ccminerKlaust which work !

**Comment by iavorstoev** [comment]
The hsr miner benchmark is not working properly with 8 x 1080ti. 
You could check the error message and the wrong hash result in the attached screenshot:

![report](https://user-images.githubusercontent.com/17744951/35616036-a01592be-067c-11e8-968d-c2c076a7fce4.png)

**Comment by gaim281** [comment]
@ruarkbg , the error above accrue only when ur hashRare is bigger then 10000GH/s so the number of hashrate*1000^2 is bigger the int.
maybe is should be $HashRate = [double]$HashRate (wrapper.ps ln 57)

@nemosminer , also when $HashRate  is bigger then 10000GH/s  other error i cant figure out, benchmark hashrate goes up to 100-1000TH/s and miner always mine neoscrypt.. this is a serious bug
my rig 8X1070ti
besides that nemosminer is really good  for me.

**Comment by ktsonevski** [comment]
Hello,
@gaim281 , I do not work at 8x1080ti, the problem continues as with @ruarkbg :(

@nemosminer, can you help us please.

Regards,

**Comment by gaim281** [comment]
@ktsonevski whats ur total hash rate ?
for my hashrate 10.5MH/s it works gr8

**Comment by ktsonevski** [comment]
Yes, and mine is just like: 10.45~10-48

**Comment by gaim281** [comment]
delete PalginNeoHashrate.txt from miner root dir and PalginHSR_NeoScrypt_HashRate.txt from stat dir
and try benchmark again

**Comment by ktsonevski** [comment]
@gaim281 
Can you upload the two config files somewhere, for example: pastebin.com

**Comment by gaim281** [comment]
@ktsonevski ,
.\stat\PalginHSR_NeoScrypt_HashRate.txt >>    https://pastebin.com/2PFYxyaM
.\PalginNeoHashrate.txt >> 10310000 (just put this value in empty PalginNeoHashrate.txt file )

as you said if we have same rates +/- so it should work without benchmark
anyway you should replace lines 52-57 in wrapper.ps1 with this code: 

switch ($Words -like "*H/s*" -replace "[0-9.,]",'' | Select-Object -Last 1) {
                "KH/s" {$HashRate *= [Math]::Pow(1000, 1)}
                "mH/s" {$HashRate *= [Math]::Pow(1000, 2)}
                "MH/s" {$HashRate *= [Math]::Pow(1000, 2)}
            }
	$HashRate = [int]$HashRate 

all the best

**Comment by kodeballer** [comment]
is this still necessary with version 2.5? Thanks

**Comment by gaim281** [comment]
@kodeballer unbelievably yes... still needed for me. 
i get 10.11TH/s instead of 10.11MH/s
dono why he didnt fix it

**Comment by nemosminer** [comment]
update Palgin Benchmark

removed = 8mins 
benchmarking is now 10mins same as all algos 
fix error when hashrate of over 10mhs  would display as 10ghs or 10ths 
special thanks to: @gaim281 for the help
sorry for delay in fixing this was much over due

https://github.com/nemosminer/NemosMiner-v2.5/commit/a4ef6f2a8630fde9678967bd9942607a6d318ead
https://github.com/nemosminer/NemosMiner-v2.5/commit/823043dbae609081b2d25586ecf06fb3a7665c5e

**Comment by nemosminer** [comment]
: ) try now sorry for delay

**Comment by nemosminer** [comment]
done
