### ISSUE TITLE
Substract fee from profit calculation

### ISSUE THREAD

**Issue by boecht** [nemosminer/NemosMiner-v2.5#248]
Especially when using multiple pools at once, it is beneficial for profit calculation to subtract the pool fee to make choosing the right pool for an algo more reliable.

In the pool file, I added `*(1-($zergpool_Request.$_.fees/100))` after (both) divisor operations when setting the stat var:
before (ahashpool):
```
28:    if ((Get-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit") -eq $null) {$Stat = Set-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit" -Value ([Double]$ahashpool_Request.$_.estimate_last24h / $Divisor)}
29:    else {$Stat = Set-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit" -Value ([Double]$ahashpool_Request.$_.estimate_current / $Divisor)}
```
after:
```
28:    if ((Get-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit") -eq $null) {$Stat = Set-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit" -Value ([Double]$ahashpool_Request.$_.estimate_last24h / $Divisor *(1-($ahashpool_Request.$_.fees/100)))}
29:    else {$Stat = Set-Stat -Name "$($Name)_$($ahashpool_Algorithm)_Profit" -Value ([Double]$ahashpool_Request.$_.estimate_current / $Divisor *(1-($ahashpool_Request.$_.fees/100)))}
```

I have only tested this with ahashpool and zergpool, I do not know if other pools also provide fee data.

**Comment by nemosminer** [comment]
thankyou

**Comment by boecht** [comment]
Same goes for miner fee (I would understand if you do not want to actually implement this, as it may make nemosminer look slower than other mining managers, maybe compensate with an entry in readme or above the statistics?):

./Miners/DSTM.ps1:
`17:        HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week *.98}  # substract 2% devfee`

./Miners/PalginHSR.ps1
`48:         HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week *.99}  # substract 1% devfee`

**Comment by nemosminer** [comment]
nice

**Comment by nemosminer** [comment]
done 

just miningpoolhub and nicehash to do nicehash is important as its 4%

**Comment by nemosminer** [comment]
done i've implement this for all pools and miners with respective fee's 

just haven't done miningpoolhub and nicehash yet...

nicehash is important as it 4% for external wallets 2-3% for internal plus withdrawal fee = 4%
