### ISSUE TITLE
Brain-2.1.ps1 can't get data from pool

### ISSUE THREAD

**Issue by ErsinErce** [nemosminer/NemosMiner-v2.5#292]
Stats were not updating till i change `$AlgoData = (Invoke-WebRequest $PoolStatusUri).content | ConvertFrom-Json` to `$AlgoData = Invoke-WebRequest $PoolStatusUri -UseBasicParsing -Headers @{"Cache-Control"="no-cache"} | ConvertFrom-Json`

**Comment by nemosminer** [comment]
thanks done
