### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by reference001** [nemosminer/NemosMiner-v2.5#302]
It's can't run what happend???
![28312645_395328367598920_1865106704_o](https://user-images.githubusercontent.com/36688891/36465659-b69399ea-1708-11e8-8d64-2519d14a07ac.png)

**Comment by isak-3drp-co-za** [comment]
I commented out line 48 and 49, as per note1, you should have an API key for MPH :-)

![image](https://user-images.githubusercontent.com/5238992/36466088-ff0430ea-16e0-11e8-94b2-0ad528e0b6e7.png)

**Comment by reference001** [comment]
Nope. It’s happend on every pool when run.

เมื่อ วันพุธที่ 21 กุมภาพันธ์ ค.ศ. 2018, isak-3drp-co-za <
notifications@github.com> เขียนว่า:

**Comment by isak-3drp-co-za** [comment]
I'm using ZPool, I assume because we do not have an API key entered for MPH, it errors out. Try commenting out the two lines and let us know?

**Comment by nemosminer** [comment]
:) fixed
i missed a " , "

**Comment by reference001** [comment]
You mean i will delete line48 49?

เมื่อ วันพุธที่ 21 กุมภาพันธ์ ค.ศ. 2018, isak-3drp-co-za <
notifications@github.com> เขียนว่า:

**Comment by nemosminer** [comment]
use latest cose... https://github.com/nemosminer/NemosMiner-v2.5/archive/master.zip

**Comment by reference001** [comment]
Thx a lot sir.

เมื่อ วันพุธที่ 21 กุมภาพันธ์ ค.ศ. 2018, nemosminer <
notifications@github.com> เขียนว่า:

**Comment by nemosminer** [comment]
your welcome

**Comment by reference001** [comment]
How Can I Fix It. Thx.
​

2018-02-21 13:37 GMT+07:00 nemosminer <notifications@github.com>:
