### ISSUE TITLE
Added device... no algos?

### ISSUE THREAD

**Issue by jagauthier** [nemosminer/NemosMiner-v2.5#305]
I added a device, which I have done in the past.  But when I launch I do not see a list of algos.

![image](https://user-images.githubusercontent.com/7101432/36483397-fe3c13e6-16e3-11e8-8132-0e547f3ff0fa.png)

**Comment by nemosminer** [comment]
Display Options

  Use -UIStyle Light or -UIStyle Full in start.bat
        Full = Usual display
        Light = Show only currently mining info (Default)
  UIStyle automaticaly swtiches to Full during benchmarking.
