### ISSUE TITLE
Excavator and bminer support

### ISSUE THREAD

**Issue by boguslawkaczalek** [nemosminer/NemosMiner-v2.5#308]
Hi

Recently there was an update to excavator (https://github.com/nicehash/excavator) and on the 1080ti it is 3-10% faster on most algorithms. Would it be a problem to add support to it?

Additionally, bminer (https://www.bminer.me) is also the fastest equihash miner available, but it's not supported in nemosminer. Would you mind adding it?

**Comment by nemosminer** [comment]
excavator=eula
bminer = i find dstm to perform really well... b miner is not much if any faster... 

which algos are you finding excavator faster on?

**Comment by sephir69** [comment]
neoscrypt for me

**Comment by boguslawkaczalek** [comment]
Excavator eula prevents you from auto download, but if user downloads it for his own, it can be used.
It is especially faster on neoscrypt. I have 3x 1080TI, plain gives 4,55 HM/s, excavator 5,24 MH/s

For BMiner, DTSM gives me ~1950 Ksol/s, Bminer 2140 KSol/s

The tests ware performed for 10 minutes using TDP 70%, Core +170, MEM +550

**Comment by nemosminer** [comment]
ok thanks
