### ISSUE TITLE
Stats missing

### ISSUE THREAD

**Issue by yepla** [nemosminer/NemosMiner-v2.5#309]
Hello i m using the last version of the git repository of NemosMiner and stats like btc/day and eur/day is missing.
I m not seeing too each line for the different algo and the mining reward :(

**Comment by nemosminer** [comment]
new to v2.5

Display Options

  Use -UIStyle Light or -UIStyle Full in start.bat
        Full = Usual display
        Light = Show only currently mining info (Default)
  UIStyle automaticaly swtiches to Full during benchmarking.
