### ISSUE TITLE
NPlusMiner-v1.3.ps1: 412 : 69 Try to divide by 0

### ISSUE THREAD

**Issue by yepla** [nemosminer/NemosMiner-v2.5#310]
I have an error by starting the last NemosMiner from git :
NPlusMiner-v1.3.ps1: 412 : 69 Try to divide by 0
+ ... -NoNewline; Write-Host " " $_.pool "Balance="$_.balance ("{0:P0}" -f ...
      + CategoryInfo : NotSpecified: (:) [], RuntimeException
      + FullyQualifiedErrorId :  RuntimeException

**Comment by nemosminer** [comment]
re

**Comment by yepla** [comment]
no
