### ISSUE TITLE
HSRMINER Neoscrypt Fork - support, attached miner file

### ISSUE THREAD

**Issue by jrafaelmdo** [nemosminer/NemosMiner-v2.5#314]
Hello Nemos,

I created the miner file for HSRMINER Neoscrypt Fork

https://bitcointalk.org/index.php?topic=2765610.0

In my systems its a bit faster than klaust and excavator.

Thanks

[HSRminer.zip](https://github.com/nemosminer/NemosMiner-v2.5/files/1748156/HSRminer.zip)

**Comment by nemosminer** [comment]
im already using it for neoscrypt....
