### ISSUE TITLE
neoscript

### ISSUE THREAD

**Issue by tiotoi** [nemosminer/NemosMiner-v2.5#315]
Hi guys, i have am issue during a benchmarking
Cannot convert value "10750000000000.00" to type "System.Int32". Error: "Value was either too large or too small for
an Int32."
At C:\NPlusMiner-1.3\Wrapper.ps1:57 char:4
+             $HashRate = [int]$HashRate
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastIConvertible

any idea how i can fix it? 
thanks a lot

**Comment by nemosminer** [comment]
it is fixed wrapper is no longer used for HSR it runs with API same as all other ccminers....
